// 应用模块（产出 Docker 镜像）- 从根 build.gradle 中获取
def microservices = rootProject.ext.appModules

switch (PROFILE) {
    case 'dev':
        ext {
            registryUrl = ''
            registryNamespace = ''
            registryUsername = ''
            registryPassword = ''
            baseImage = 'amazoncorretto:17.0.8'
        }
        break
    case 'prod':
        ext {
            registryUrl = ''
            registryNamespace = ''
            registryUsername = ''
            registryPassword = ''
            baseImage = 'amazoncorretto:17.0.8'
        }
        break
}

println "build services: ${microservices.name}"
println "build profile: $PROFILE"

File agentFile = file './skywalking-agent'

configure(microservices) {
    apply plugin: 'com.google.cloud.tools.jib'
    jib {
        from {
            image = "${baseImage}"
        }
        to {
            image = "${registryUrl}/${registryNamespace}/${project.name}:${project.version}"
            auth {
                username = "${registryUsername}"
                password = "${registryPassword}"
            }
        }
        allowInsecureRegistries = true
        container {
            environment = [SW_AGENT_NAME: "${project.name}".toString()]
            if (project.name == 'matrix-admin') {
                jvmFlags = ['-Djava.security.egd=file:/dev/./urandom', '-Dfile.encoding=utf-8']
            } else {
                jvmFlags = ['-Djava.security.egd=file:/dev/./urandom', '-Dfile.encoding=utf-8', '-javaagent:/skywalking-agent/skywalking-agent.jar']
            }
            creationTime = 'USE_CURRENT_TIMESTAMP'
            volumes = ['/skywalking/agent']
        }

        // matrix-admin 不挂 SkyWalking agent
        if (project.name == 'matrix-admin') {
            return
        }
        extraDirectories {
            paths {
                path {
                    from = agentFile
                    into = '/skywalking-agent'
                }
            }
        }
    }
}
