# =========== Project ===========
PROFILE=dev
VERSION=3.0.0
GROUP=com.matrix
DEVELOPER_NAME=zhaoWeiLong
DEVELOPER_EMAIL=zhaoweilong176@gmail.com

# =========== Gradle ===========
GRADLE_VERSION=8.14.3
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# 启用配置缓存（实验性，问题降为警告）
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

# =========== SonarQube ===========
#sonar.projectKey=your-project-key
#sonar.projectName=matrix-cloud
#sonar.host.url=http://localhost:9000
#sonar.token=your-token
