-- 测试数据清理脚本，每个测试方法执行后自动运行（BaseDbUnitTest 配置）
-- 如需针对特定表添加清理逻辑，请在子类中覆盖 @Sql 注解路径
SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE sys_admin RESTART IDENTITY;
TRUNCATE TABLE sys_role RESTART IDENTITY;
TRUNCATE TABLE sys_menu RESTART IDENTITY;
TRUNCATE TABLE sys_resource RESTART IDENTITY;
TRUNCATE TABLE sys_role_menu RESTART IDENTITY;
TRUNCATE TABLE sys_admin_role RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
