apply plugin: "java-platform"

javaPlatform {
    allowDependencies()
}

def v = libs.versions

dependencies {
    constraints {
        // === Spring Boot Starters ===
        api libs.mybatis.plus
        api libs.easy.es
        api libs.redisson
        api libs.lock4j
        api libs.druid
        api libs.sa.token.spring.boot4
        api libs.sa.token.reactor
        api libs.mybatis.plus.join
        api libs.bean.searcher
        api libs.spring.boot.admin.server
        api libs.dynamic.datasource
        api libs.easy.trans
        api libs.sms4j

        // === Other ===
        api libs.sentinel.core
        api libs.sa.token.redisson
        api libs.sa.token.jwt
        api libs.sa.token.core
        api libs.xxl.job
        api libs.bean.searcher.core
        api libs.easy.trans.mybatis
        api libs.easy.trans.anno

        // === APM 监控 ===
        api libs.skywalking.toolkit.logback
        api libs.skywalking.toolkit.trace
        api libs.skywalking.toolkit.opentracing
        api libs.micrometer.prometheus

        // === Utils ===
        api libs.streamex
        api libs.hutool
        api libs.guava
        api libs.gson
        api libs.fastjson2
        api libs.commons.pool2
        api libs.caffeine
        api libs.transmittable.thread.local
        api libs.commons.lang3
        api libs.commons.collections4
        api libs.easyexcel
        api libs.user.agent.utils
        api libs.httpclient5

        api libs.swagger.annotations
        api libs.swagger.models
        api libs.mybatis.plus.extension
        api libs.mybatis.plus.generator
        api libs.mybatis.plus.annotation
        api libs.mybatis.plus.core
        api libs.mybatis.plus.jsqlparser

        api libs.vavr
        api libs.jool
        api libs.joda.money
        api libs.servlet.api
        api libs.validation.api
        api libs.tiny.pinyin
        api libs.lombok

        // === 第三方 SDK ===
        api libs.ons.client
        api libs.wx.miniapp

        // === 其他 ===
        api libs.jcl.over.slf4j
        api libs.java.jwt
        api libs.jwks.rsa
        api libs.pinyin4j
    }
}
