dependencies {
    api project(':matrix-core:matrix-auto')
    api 'com.mysql:mysql-connector-j'
    api 'com.alibaba:druid-spring-boot-4-starter'
    api 'com.github.yulichang:mybatis-plus-join-boot-starter'
    api 'com.baomidou:mybatis-plus-spring-boot4-starter'
    api 'com.baomidou:dynamic-datasource-spring-boot4-starter'
    api 'cn.zhxu:bean-searcher-boot-starter'
    api 'com.baomidou:mybatis-plus-jsqlparser'

    compileOnly project(':matrix-core:matrix-api')
    compileOnly project(':matrix-core:matrix-crypto')
    compileOnly 'com.alibaba.csp:sentinel-core'
    compileOnly 'io.micrometer:micrometer-core'
    compileOnly libs.mica.auto
    annotationProcessor libs.mica.auto

}
