dependencies {
    api project(':matrix-core:matrix-auto')
    api libs.mica.ip2region

    implementation project(':matrix-core:matrix-feign')
    implementation project(':matrix-core:matrix-prometheus')

    compileOnly 'org.aspectj:aspectjweaver'
    compileOnly 'org.springframework:spring-web'
}
