spring:
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
    encoding: utf-8
    fallback-to-system-locale: true
  # redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    timeout: 10s
    password: ${REDIS_PASSWORD:matrix}
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  cache:
    type: redis
  cloud:
    sentinel:
      enabled: true
      eager: true
      transport:
        port: ${SENTINEL_PORT:8719}
        dashboard: ${SENTINEL_DASHBOARD:localhost:8088}
seata:
  config:
    type: nacos
    nacos:
      server-addr: ${NACOS_SERVER_ADDRESS:localhost:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWD:nacos}
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${NACOS_SERVER_ADDRESS:localhost:8848}
      group: SEATA_GROUP
      cluster: default
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWD:nacos}

# 端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always