spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 300
  cache:
    type: redis

  # spring cloud配置
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        file-extension: yaml
    sentinel:
      enabled: true
      eager: true
      transport:
        port: 8719
        dashboard: localhost:8080
        client-ip: 192.168.2.99

# feign配置
feign:
  ## 启用对 feign 的 Sentinel 支持
  sentinel:
    enabled: true
  client:
    refresh-enabled: true
    config:
      default:
        logger-level: full

# 端点配置
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 文档配置
knife4j:
  enable: true
  production: false
  cors: true

# mybatis plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  check-config-location: false


  sa-token:
    # jwt秘钥
    jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk
    # token名称 (同时也是cookie名称)
    token-name: Authorization
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: 1800
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: true