spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDRESS:localhost:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWD:nacos}
      config:
        file-extension: yaml
        import-check:
          enabled: false
    config:
      import:
        - optional:nacos:application-common.yml
        - optional:nacos:${spring.application.name}.yml
seata:
  config:
    type: nacos
    nacos:
      server-addr: ${NACOS_SERVER_ADDRESS:localhost:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWD:nacos}
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${NACOS_SERVER_ADDRESS:localhost:8848}
      group: SEATA_GROUP
      cluster: default
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWD:nacos}

logging:
  file:
    path: /var/logs
  level:
    com.matrix.mapper: debug
    com.matrix.api.**: debug