server:
  port: 10000

spring:
  application:
    name: docApp
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos
    serviceAuth:
      enable: true
      username: nacos
      password: nacos
  basicAuth:
    enable: true
    username: admin
    password: admin