version: "2"
services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos
    env_file:
      - ./nacos-standlone-mysql.env
    volumes:
      - /usr/nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always