spring:
  cloud:
    ## ancos配置
    nacos:
      config:
        file-extension: yaml

    ## gateway配置
    gateway:
      globalcors:
        ## 配置跨域
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: baidu
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu
          filters:
            - RedirectTo=302,http://www.baidu.com
        - id: demo
          uri: lb://demoApp
          predicates:
            - Path=/hello/**

    ## sentinel配置
    sentinel:
      scg:
        fallback:
          content-type: application/json
          mode: response
          response-status: 429
          response-body: '{"message":"Too Many Requests"}'
      datasource:
        gw-flow:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            data-id: gateway-flow
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw_flow
        gw-api-group:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            data-id: gateway-api-group
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw_api_group


matrix:
  swagger:
    name: api-gateway
    version: 1.0.0
    description: api网关
  security:
    whiteUrls:
      - /user/**



sa-token:
  # jwt秘钥
  jwt-secret-key: asdasdasifhueuiwyurfewbfjsdafjk
