spring:
  # redis配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/matrix?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    ## ancos配置
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        file-extension: yaml

    ## sentinel配置
    sentinel:
      enabled: true
      eager: true
      transport:
        port: 8719
        dashboard: localhost:8080
        client-ip: 192.168.2.99
      scg:
        fallback:
          content-type: application/json
          mode: response
          response-status: 429
          response-body: '{"message":"Too Many Requests"}'
      datasource:
        gw-flow:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            data-id: gateway-flow
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw_flow
        gw-api-group:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            data-id: gateway-api-group
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw_api_group


matrix:
  security:
    whiteUrls:
      - /auth/**
  tenant:
    enable: true
    ignoreTables:
      - tenant




logging:
  level:
    com.matrix.mapper: debug