timeout: 5s

targets:
  webhook_robot:
    # 钉钉机器人创建后的webhook地址
    url: https://oapi.dingtalk.com/robot/send?access_token=
  webhook_mention_all:
    # 钉钉机器人创建后的webhook地址
    url: https://oapi.dingtalk.com/robot/send?access_token=
    # 提醒全员
    mention:
      all: true
    #指定用户
#  webhook_mention_users:
#    url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
#    mention:
#      mobiles: ['156xxxx8827', '189xxxx8325']
## Targets, previously was known as "profiles"
