version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    hostname: nacos
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./log/nacos:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    image: example/mysql:8.0.30
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./redis/conf:/redis/config
      # 数据文件
      - ./redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    restart: always

  sentinel:
    # https://github.com/lk0423/sentinel-dashboard
    image: linking0606/sentinel-dashboard:${SENTINEL_VERSION}
    container_name: sentinel
    environment:
      PARAM: -Dserver.port=8088 -Dcsp.sentinel.dashboard.server=localhost:8088 -Dproject.name=sentinel-dashboard -Ddatasource.provider=nacos -Ddatasource.provider.nacos.server-addr=nacos:8848 -Ddatasource.provider.nacos.username=nacos -Ddatasource.provider.nacos.password=nacos
      TZ: Asia/Shanghai"
    ports:
      - "8088:8088"
    restart: always
    depends_on:
      - nacos

  seata-server:
    image: seataio/seata-server:${SEATA_VERSION}
    container_name: seata-server
    hostname: seata-server
    env_file:
      - ./env/seata.env
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "8091:8091"
      - "7091:7091"
    volumes:
      # 假设我们通过docker cp命令把资源文件拷贝到相对路径`./seata-server/resources`中
      - ./seata:/seata-server/resources
    restart: always
    privileged: true
    depends_on:
      - nacos