version: '3.8'
networks:
  default:
    external: true
    name: matrix_cloud


services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./prometheus/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always
    user: "0"
    networks:
      - default

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - default

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always
    networks:
      - default

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/:/var/run/:rw
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      #      - /var/lib/docker/:/var/lib/docker:ro #linux使用此配置，注释下行配置
      - /mnt/wsl/docker-desktop-data/version-pack-data/community/docker/:/rootfs/var/lib/docker:ro #仅适用于window的wsl2配置，挂载docker，否则无法查看容器
    ports:
      - 8081:8080
    restart: always
    privileged: true
    networks:
      - default

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    environment:
      DATA_SOURCE_NAME: root:matrix@tcp(mysql:3306)/performance_schema
    ports:
      - 9104:9104
    restart: always
    networks:
      - default

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    hostname: redis_exporter
    restart: always
    ports:
      - "9121:9121"
    command:
      - "--redis.addr=redis://redis:6379"
      - "--redis.password=matrix"
    networks:
      - default