version: '3.8'
networks:
  default:
    external: true
    name: matrix_cloud


services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/node_down.yml:/etc/prometheus/node_down.yml
    ports:
      - 9090:9090
    restart: always
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./prometheus/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always
    user: "0"
    networks:
      - default

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - default

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always
    networks:
      - default

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/:/var/run/:rw
      - /sys:/sys:ro
      - /mnt/wsl/docker-desktop-data/version-pack-data/community/docker/:/rootfs/var/lib/docker:ro #仅适用于window的wsl2配置，挂载docker，否则无法查看容器
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    ports:
      - 8081:8080
    restart: always
    privileged: true
    networks:
      - default
