version: '3'

services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    hostname: mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: matrix
      # 初始化数据库
      MYSQL_DATABASE: matrix
    ports:
      - "3306:3306"
    volumes:
      # 数据挂载
      - ./mysql/data/:/var/lib/mysql/
      # 配置挂载
      - ./mysql/conf/:/etc/mysql/conf.d/
    command:
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      - matrix

  redis:
    image: redis:6.2.7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./redis/conf:/redis/config
      # 数据文件
      - ./redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    restart: always
    networks:
      - matrix

  nacos:
    container_name: nacos
    image: nacos/nacos-server:latest
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    environment:
      # JVM大小参数
      - JVM_XMS=128m   #-Xms default :2g
      - JVM_XMX=128m   #-Xmx default :2g
      - JVM_XMN=32m   #-Xmn default :1g
      - JVM_MS=16m     #-XX:MetaspaceSize default :128m
      - JVM_MMS=16m    #-XX:MaxMetaspaceSize default :320m
      - NACOS_DEBUG=n  #是否开启远程debug，y/n，默认n
      - TOMCAT_ACCESSLOG_ENABLED=false #是否开始tomcat访问日志的记录，默认false
    volumes:
      - ./log/nacos:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
      - "9555:9555"
    restart: always
    networks:
      - matrix
    depends_on:
      - mysql

  sentinel:
    image: linking0606/sentinel-dashboard:1.8.5 # https://github.com/lk0423/sentinel-dashboard/blob/master/
    container_name: sentinel
    environment:
      - "PARAM=-Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858 -Dproject.name=sentinel-dashboard -Ddatasource.provider=nacos -Ddatasource.provider.nacos.server-addr=nacos:8848 -Ddatasource.provider.nacos.username=nacos -Ddatasource.provider.nacos.password=nacos"
    ports:
      - "8858:8858"
    restart: always
    networks:
      - matrix
    depends_on:
      - nacos

networks:
  matrix:
    driver: bridge

