# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9093' ]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "node_down.yml"
  - "galera.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
        labels:
          instance: cadvisor

  - job_name: 'node-exporter'
    scrape_interval: 8s
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          instance: node-exporter

  - job_name: 'alertmanager'
    static_configs:
      - targets: [ 'alertmanager:9093' ]
        labels:
          instance: alertmanager

  - job_name: 'mysqld'
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]
        labels:
          instance: mysql

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis_exporter:9121' ]
        labels:
          instance: redis

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway:9000' ]
        labels:
          instance: gateway

  - job_name: 'system-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'system-server:9001' ]
        labels:
          instance: system-server