spring:
  cloud:
    ## sentinel配置
    sentinel:
      filter:
        enabled: false
      scg:
        fallback:
          content-type: application/json
          mode: response
          response-status: 429
          response-body: '{"message":"Too Many Requests"}'
      datasource:
        gw-flow:
          nacos:
            server-addr: ${NACOS_SERVER_ADDRESS:nacos:8848}
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWD:nacos}
            data-id: gateway-flow
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw_flow
        gw-api-group:
          nacos:
            server-addr: ${NACOS_SERVER_ADDRESS:nacos:8848}
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWD:nacos}
            data-id: gateway-api-group
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw_api_group
    ## gateway配置
    gateway:
      globalcors:
        ## 配置跨域
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          url-expression: "'grayLb://'+serviceId"
      loadbalancer:
        use404: true