# 以下配置可以配置在nacos中
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_HOST:192.168.2.134:3306}/${DATASOURCE_NAME:matrix}?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}

matrix:
  swagger:
    enable: true
    name: 系统服务
    version: 1.0.0
    description: 系统服务接口文档
  tenant:
    enable: true
    ignoreTables:
      - tenant
    ignore-urls:
      - /auth/**
  security:
    white-urls:
      - /auth/**