server:
  port: 10000

spring:
  application:
    name: docApp
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDRESS:localhost:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWD:nacos}

knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://${NACOS_SERVER_ADDRESS:localhost:8848}/nacos
    serviceAuth:
      enable: true
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWD:nacos}
  basicAuth:
    enable: true
    username: admin
    password: admin