# 安全配置
security:
  # 验证码
  captcha:
    # 是否开启验证码
    enabled: true
    # 验证码类型 math 数组计算 char 字符验证
    type: MATH
    # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
    category: CIRCLE
    # 数字验证码位数
    numberLength: 1
    # 字符验证码长度
    charLength: 4
  # 防止XSS攻击
  xss:
    enabled: false
  # 不校验白名单
  ignore:
    whites:
      - /actuator/health
      - /doc.html
      - /code
      - /v3/api-docs/**
      - /*/v3/api-docs/**
      - /csrf
      - /webjars/**
      - /system/auth/**


spring:
  cloud:
    sentinel:
      datasource:
        gw_flow:
          nacos:
            server-addr: ${NACOS_SERVER_ADDRESS:nacos:8848}
            namespace: ${spring.profiles.active}
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWD:nacos}
            data-id: sentinel_rule_config-matrix-gateway-gateway-flow-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: gw_flow
        gw-api-group:
          nacos:
            server-addr: ${NACOS_SERVER_ADDRESS:nacos:8848}
            namespace: ${spring.profiles.active}
            username: ${NACOS_USERNAME:nacos}
            password: ${NACOS_PASSWD:nacos}
            data-id: sentinel_rule_config-matrix-gateway-gateway-api-group
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: gw_api_group
    gateway:
      allowOrigins:
        - http://localhost:8891
        - http://127.0.0.1:3000
        - http://localhost:3000
        - http://localhost:8889
        - http://localhost:8080
        - http://127.0.0.1:8848

      httpclient:
        connect-timeout: 5000
        response-timeout: 60s

      requestLog: true
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
          url-expression: "'grayLb://'+serviceId"
      routes:
        - id: system
          uri: grayLb://matrix-system
          predicates:
            - Path=/system/**
          filters:
            # - name: RequestRateLimiter
            #   args:
            #     key-resolver: "#{@remoteAddrKeyResolver}"
            #     redis-rate-limiter.burstCapacity: 20 # 令牌桶的容量，允许在一秒钟内完成的最大请求数
            #     redis-rate-limiter.replenishRate: 20 # 允许用户每秒处理多少个请求
            - StripPrefix=1
        - id: resource
          uri: grayLb://matrix-resource
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1



knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: 系统服务
        url: /system/v3/api-docs
        service-name: matrix-system
        context-path: system
        order: 1
      - name: 资源服务
        url: /resource/v3/api-docs
        service-name: matrix-resource
        context-path: resource
        order: 2



feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: none
