sms:
  smsValidateIgnore:
  isPrint: false
  config-type: yaml
  blends:
    alibaba:
      supplier: alibaba
      access-key-id:
      access-key-secret:
      signature:


jpush:
  config:
    TEST:
      appKey:
      masterSecret:
      apnsProduction:
      privateKey:
aliyun:
  oss:
    accessKeyId:
    accessKeySecret:
    endpoint:
    bucketName:
    prefix:
matrix:
  tenant:
    enable: true
  ignoreTables:
    - sys_contact_log
  ignore-urls:
    - /resource/ip/**
  swagger:
    enabled: true
    title: 资源服务
    version: 1.0
    description: oss、sms、email、jpush服务
    contact-user: zwl
    contact-url: http://localhost:9003/v3/api-docs
  mq:
    enabled: false
    onsAddr:
    accessKey:
    secretKey:
    producers:
    consumers:
