spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${DATASOURCE_HOST:127.0.0.1:3306}/${DATASOURCE_DB:matrix}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true&allowPublicKeyRetrieval=true
          username: ${DATASOURCE_USERNAME:root}
          password: ${DATASOURCE_PASSWORD:matrix}
          driver-class-name: com.mysql.cj.jdbc.Driver


sms:
  smsValidateIgnore:
  isPrint: false
  config-type: yaml
  blends:
    alibaba:
      supplier: alibaba
      access-key-id:
      access-key-secret:
      signature:


jpush:
  config:
    TEST:
      appKey:
      masterSecret:
      apnsProduction:
      privateKey:
aliyun:
  oss:
    accessKeyId:
    accessKeySecret:
    endpoint:
    bucketName:
    prefix:
matrix:
  tenant:
    enable: true
  ignoreTables:
    - sys_contact_log
  ignore-urls:
    - /resource/ip/**
  mq:
    enabled: false
    onsAddr:
    accessKey:
    secretKey:
    producers:
    consumers:
