matrix:
  tenant:
    enable: true
    ignore-urls:
      - /auth/**
      - /v3/api-docs
      - /easyTrans/proxy/**
    ignoreTables:
      - sys_menu
      - sys_role_menu
      - sys_user_role
      - sys_config
      - sys_dict_data
      - sys_dict_type
      - sys_region_dict

  load-balance:
    gray:
      enabled: true
      chooser: com.matrix.feign.chooser.ProfileRuleChooser
      ips:
        - 192.168.31.19
  monitor:
    traceEnable: true
    metricsEnable: true
  swagger:
    enabled: true
    title: 系统服务
    version: 0.0.1
    description: 系统基础服务
    contact-user: zwl
    contact-email: zhaoweilong176@gmail.com
    contact-url: http://localhost:9004/v3/api-docs

  mq:
    enabled: true
    onsAddr: xxxxxxxxx
    accessKey: xxxxxxxxx
    secretKey: xxxxxxxxx
    producers:
      - groupId: GID_ws_notify_subscribe
      - groupId: GID_sys_user_data
    consumers:
      - groupId: GID_ws_notify_subscribe
        MessageModel: BROADCASTING