groups:
  - name: node_down
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          user: test
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
  - name: MySQLdAlerts
    rules:
      - alert: MySQLDown
        expr: mysql_up != 1
        for: 5m
        labels:
          severity: critical
        annotations:
          description: 'MySQL {{$labels.job}} on {{$labels.instance}} is not up.'
          summary: MySQL not up.